# Generated by Django 3.1.3 on 2020-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='text',
        ),
        migrations.AddField(
            model_name='impression',
            name='comment',
            field=models.TextField(default=None, verbose_name='Комментарий воспоминания'),
        ),
        migrations.AddField(
            model_name='impression',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Заголовок воспоминания'),
        ),
    ]
